sudo: required
services:
  - docker

before_install:
  - docker build -t jonathanhoward/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true jonathanhoward/docker-react-practice npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-practice"
  env: "DockerReactPractice-env"
  bucket_name: "elasticbeanstalk-us-east-1-196749790459"
  bucket_path: "docker-react-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"