sudo: required
services:
  - docker

before_install:
  - docker build -t jonathanhoward/docker-react-practice -f Dockerfile.dev .

script:
  - docker run jonathanhoward/docker-react-practice npm run test -- --coverage